---
title: "Surface ECG annotations on EGM data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Surface ECG annotations on EGM data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(shiva)
```


We first get the ECG-based annotation data.
Ensure matching signal lengths for simplicity of beat/signal annotation.

```{r}
# Annotation data
ann <- read_annotation(
	record = "sample",
	annotator = "qrs",
	record_dir = test_path(),
	wfdb_path = "/usr/local/bin"
)

# Keep only relevant sample points
ann <- ann[2:3]
ann$Type[which(ann$Type == "N")] <- "qrs_peak"
ann$Type[which(ann$Type == "p")] <- "p_peak"
ann$Type[which(ann$Type == "t")] <- "t_peak"
head(ann)

# Change the format of annotations to be informative of P-start and P-end, etc
pw <-
  rbind(ann[which(ann$Type == "p_peak") - 1,],
        ann[which(ann$Type == "p_peak"),],
        ann[which(ann$Type == "p_peak") + 1,])
pw$Type[pw$Type == "("] <- "start"
pw$Type[pw$Type == "p_peak"] <- "peak"
pw$Type[pw$Type == ")"] <- "end"

qrs <-
  rbind(ann[which(ann$Type == "qrs_peak") - 1,],
        ann[which(ann$Type == "qrs_peak"),],
        ann[which(ann$Type == "qrs_peak") + 1,])
qrs$Type[qrs$Type == "("] <- "start"
qrs$Type[qrs$Type == "qrs_peak"] <- "peak"
qrs$Type[qrs$Type == ")"] <- "end"

tw <-
  rbind(ann[which(ann$Type == "t_peak") - 1,],
        ann[which(ann$Type == "t_peak"),],
        ann[which(ann$Type == "t_peak") + 1,]) |>
  rbind(qrs[qrs$Type == "end", ])
tw$Type[tw$Type == "end"] <- "start"
tw$Type[tw$Type == "("] <- "start"
tw$Type[tw$Type == "t_peak"] <- "peak"
tw$Type[tw$Type == ")"] <- "end"

# Reshape into wide format
pw$beat <- rep(c(1:3), 3)
qrs$beat <- rep(c(1:6), 3)
tw$beat <- rep(c(1:1), 3)

pw <- tidyr::pivot_wider(pw, id_cols = beat, names_from = Type, values_from = Sample)
qrs <- tidyr::pivot_wider(qrs, id_cols = beat, names_from = Type, values_from = Sample)
tw <- tidyr::pivot_wider(tw, id_cols = beat, names_from = Type, values_from = Sample)
```


```{r}
egm <- read_wfdb(
	record = "sample",
	record_dir = test_path(),
	wfdb_path = "/usr/local/bin",
	begin = 0,
	units = "digital"
)

# Massage data into vertical for plotting
names(egm)[1] <- "Sample"
max_time <- max(ann$Sample)

egm_long <-
  egm[Sample >= 500 & Sample <= 3100, c("Sample", "I", "III", "V1", "CS 1-2", "CS 3-4", "CS 7-8", "CS 9-10", "HIS D", "RV 1-2")] |>
  data.table::melt(id.vars = "Sample", variable.name = "Channel", value.name = "mV") 

head(egm_long)
```

We will plot these signals and add needed layers or annotations. The annotations are to help identify "regions" within the graph - in this case, of P wave duration, QRS duration, T wave duration, etc. 

```{r}
hea <- read_lspro_header(test_path("sample-egm.txt"))
colors <- data.frame(Channel = hea$channels$label, Color = color_channels(x = hea$channels$label, palette = "material"))
ds <- merge(egm_long, colors, by = "Channel") 

# Simple version
g <- 
  ggplot(ds, aes(x = Sample, y = mV, color = Color)) +
  geom_line() +
  facet_wrap(~ Channel,
             ncol = 1,
             scales = "free_y",
             strip.position = "left") +
  scale_color_identity() +
  theme_egm_light()

g
```


```{r}

fp <- system.file("extdata", "avnrt.txt", package = "shiva")
egm_data <- read_lspro(fp)

# Basic signal plot of egms
g <-
	ggm(data = egm_data,
			channels = c("I", "CS", "HIS", "DD", "RV"),
			time_frame = c(0, 1)) |>
	add_colors(palette = "material", mode = "light") +
	scale_x_continuous(breaks = seq(0, 1, by = 0.2), labels = c("0 ms", "200 ms", "400 ms", "600 ms", "800 ms", "1000 ms"))
```

```{r}
# Find intervals for the His signal
dt <- as.data.table(g$data)
channel <- "HIS D"

# Subset data for an annotation channel
ann <- dt[label == channel]
t <- ann$index
pks <-
	gsignal::findpeaks(
		ann$mV,
		MinPeakHeight = 300,
		MinPeakDistance = 30,
		MinPeakWidth = 10,	
		DoubleSided = TRUE
	)

pks_df <- 
	data.frame(index = pks$loc, mV = pks$pks) |>
	subset(x = _, mV > 0) |>
	subset(x = _, mV < 1500)

pks_ann <- ann[index %in% pks_df$index, ]

# Find peaks and intervals, and trim data for mapping purposes
n <- seq_along(pks_ann$index)
gHis <- lapply(n, function(.x) {
	geom_text(
		data = pks_ann,
		aes(
			x = time,
			y = mV,
			label = "His"
		),
		nudge_y = 3000,
		color = "black",
		inherit.aes = FALSE
	)
})

g + 
	gHis +
	labs(title = "EGMs of AVNRT with automated His annotation",
			 caption = "Abbreviations: EGM = intracardiac electrogram, AVNRT = AV nodal re-entry tachycardia.")
```

