---
title: "Getting Started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting Started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(egm)
```

# Surface recordings

Here is a simple example of taking a MUSE XML file and converting it to digital signal.

```{r}
# Read in data
fp <- system.file('extdata', 'muse-sinus.xml', package = 'egm')
xml <- readLines(fp)
head(xml)

# Instead, can read this in as a MUSE XML file
# Now as an `egm` class
ecg <- read_muse(fp)
ecg

# Can now plot this easily
ggm(ecg)
```

# Intracardiac recordings

This signal now comes from the LSPro data.

```{r}
# Read in data
fp <- system.file('extdata', 'lspro-avnrt.txt', package = 'egm')
lspro <- readLines(fp)
head(lspro, n = 20)

# Instead, read this as signal, breaking apart header and signal data
# Presented as an `egm` class object
egm <- read_lspro(fp)
egm

# Similarly, can be visualized with ease
ggm(egm, channels = c('HIS', 'CS', 'RV'), mode = NULL) +
	theme_egm_dark() 
```

