// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// approximate_entropy.cpp
double calculate_approximate_entropy_cpp(cpp11::writable::doubles x, int m, double r);
extern "C" SEXP _EGM_calculate_approximate_entropy_cpp(SEXP x, SEXP m, SEXP r) {
  BEGIN_CPP11
    return cpp11::as_sexp(calculate_approximate_entropy_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::writable::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<int>>(m), cpp11::as_cpp<cpp11::decay_t<double>>(r)));
  END_CPP11
}
// code.cpp
void fun();
extern "C" SEXP _EGM_fun() {
  BEGIN_CPP11
    fun();
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_EGM_calculate_approximate_entropy_cpp", (DL_FUNC) &_EGM_calculate_approximate_entropy_cpp, 3},
    {"_EGM_fun",                               (DL_FUNC) &_EGM_fun,                               0},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_EGM(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
