# Generated by cpp11: do not edit by hand

calculate_approximate_entropy_cpp <- function(x, m, r) {
  .Call(`_EGM_calculate_approximate_entropy_cpp`, x, m, r)
}

fun <- function() {
  invisible(.Call(`_EGM_fun`))
}
