### Class Definitions ----

# The `ECG` class exists to carry one guarantee: every channel it holds is a
# recognised surface ECG lead. Several analyses in this package are defined only
# on the body-surface potential, and applied to an intracardiac channel they
# return a number rather than an error. `require_ECG()` is the single gate those
# functions pass through, so the check is written once rather than re-derived at
# each call site.

#' Electrocardiogram data class for 12-lead ECG studies
#'
#' @description A specialization of the [EGM] class for the standard 12-lead
#'   surface electrocardiogram. It carries the same three components - signal,
#'   header, and annotation - and adds the guarantee that every channel is a
#'   recognised surface ECG lead, named canonically.
#'
#' @details An electrophysiology study records surface and intracardiac channels
#'   side by side, so the 12-lead ECG is often a subset of a larger record.
#'   [as_ECG()] extracts that subset: it keeps the surface leads, renames them to
#'   their canonical form (`I`, `II`, `III`, `AVF`, `AVL`, `AVR`, `V1` ... `V6`),
#'   and discards every other channel. This is the intended route from a study to
#'   an ECG analysis.
#'
#'   Functions that are only defined on the surface ECG - [extract_f_waves()],
#'   [vcg()] - coerce their input through that same path and then check that the
#'   leads each one needs are actually present. A record carrying only intracardiac channels is an error
#'   rather than a silent result.
#'
#'   Construction is otherwise identical to [EGM()]. A record with a lead set
#'   that is not the standard twelve is accepted with a warning, since partial
#'   surface sets are common and several analyses tolerate them.
#'
#'   Leads are held in the order the source record wrote them, which is not
#'   always the display order and is not always the same order twice: a MUSE
#'   export and a PhysioNet record disagree about where the augmented limb leads
#'   sit. Index by name rather than by position, and use [ecg_leads()] and
#'   [lead_factor()] where an order is needed - for a plot, a sort, or the
#'   columns of a matrix stacked across records.
#'
#' @returns An object of class `ECG`, which inherits from `EGM`, containing
#'   signal, header, and annotation components.
#'
#' @param x An `ECG` object to be used with support functions
#'
#' @param signal A `signal_table` object generated by the [signal_table()]
#'   function containing standard ECG leads
#'
#' @param header A `header_table` object generated by the [header_table()]
#'   function
#'
#' @param annotation A `annotation_table` object generated by the
#'   [annotation_table()] function
#'
#' @param ... Additional arguments to be passed to the function
#'
#' @seealso [as_ECG()] to extract the surface leads from a study, [EGM()] for the
#'   general class.
#'
#' @name ECG
#' @export
ECG <- function(
  signal = signal_table(),
  header = header_table(),
  annotation = annotation_table(),
  ...
) {
  # Create a new ECG object
  new_ECG(signal, header = header, annotation = annotation)
}

#' @keywords internal
new_ECG <- function(
  signal = signal_table(),
  header = header_table(),
  annotation = annotation_table(),
  ...
) {
  # Validate that this is appropriate 12-lead ECG data
  validate_ecg_data(signal, header)

  # Convert annotation to list format (same logic as new_egm)
  if (inherits(annotation, "annotation_table")) {
    if (nrow(annotation) == 0) {
      # Empty annotation_table → unnamed list with single empty annotation_table
      annotation <- list(annotation)
    } else {
      # Non-empty annotation_table → named list with annotator name
      annotator_name <- attr(annotation, "annotator")
      if (
        is.null(annotator_name) ||
          length(annotator_name) == 0 ||
          is.na(annotator_name) ||
          annotator_name == ""
      ) {
        annotator_name <- "default"
      }
      annotation <- setNames(list(annotation), annotator_name)
    }
  } else if (is.list(annotation)) {
    if (length(annotation) == 0) {
      # Empty list → convert to unnamed list with empty annotation_table
      annotation <- list(annotation_table())
    } else {
      # Non-empty list → validate structure
      valid <- all(vapply(annotation, inherits, logical(1), "annotation_table"))
      if (!valid) {
        stop(
          "All elements in annotation list must be annotation_table objects",
          call. = FALSE
        )
      }
      # Check if this is an unnamed list with a single empty annotation_table
      is_empty_unnamed <- is.null(names(annotation)) &&
        length(annotation) == 1 &&
        nrow(annotation[[1]]) == 0
      if (!is_empty_unnamed) {
        # Non-empty annotations must be named
        if (is.null(names(annotation)) || any(names(annotation) == "")) {
          stop(
            "annotation list must be named with annotator identifiers",
            call. = FALSE
          )
        }
      }
    }
  } else {
    # If not annotation_table or list, convert to unnamed list with empty annotation_table
    annotation <- list(annotation_table())
  }

  # Create an EGM object first, then add the ECG class
  structure(
    list(
      signal = signal,
      header = header,
      annotation = annotation
    ),
    class = c('ECG', 'EGM', 'list')
  )
}

#' Validate that signal data represents a standard 12-lead ECG
#' @param signal A signal_table object
#' @param header A header_table object
#' @return TRUE if valid, throws error otherwise
#' @keywords internal
validate_ecg_data <- function(signal, header) {
  if (nrow(signal) == 0) {
    return(TRUE)
  } # Empty signal is valid initially

  # Get lead names (exclude sample column)
  lead_names <- names(signal)[-1]

  if (length(lead_names) != 12) {
    warning(
      "ECG should contain 12 leads, found ",
      length(lead_names),
      ". Converting to ECG class anyway."
    )
    return(TRUE)
  }

  non_standard <- setdiff(lead_names, unname(surface_leads(lead_names)))
  if (length(non_standard) > 0) {
    warning(
      "Non-standard ECG lead names detected: ",
      paste(non_standard, collapse = ", "),
      ". Converting to ECG class anyway."
    )
  }

  TRUE
}

#' @export
format.ECG <- function(x, ...) {
  # Call the parent format method
  NextMethod()

  # Add ECG-specific information
  n <- length(surface_leads(names(x$signal)[-1]))
  cat('Type: ', n, ' of 12 surface ECG leads\n', sep = '')

  # Return invisibly for chaining
  invisible(x)
}

#' @export
print.ECG <- function(x, ...) {
  format(x)
}

#' @export
#' @rdname ECG
is_ECG <- function(x) {
  inherits(x, "ECG")
}

# Surface leads ----------------------------------------------------------------

#' The twelve surface leads, in the order they are displayed
#'
#' @description
#'
#' `r lifecycle::badge("experimental")`
#'
#' `ecg_leads()` returns the standard twelve leads as an ordered factor.
#' `lead_factor()` puts a set of lead labels onto that order, whatever they were
#' called and whatever sequence they arrived in.
#'
#' @details The display sequence is the AHA/ACCF/HRS one (Kligfield et al.
#'   2007): the three bipolar limb leads, the three augmented limb leads, and
#'   then the precordials left to right.
#'
#'   \deqn{\text{I, II, III, aVR, aVL, aVF, V1, V2, V3, V4, V5, V6}}{I, II, III,
#'   aVR, aVL, aVF, V1, V2, V3, V4, V5, V6}
#'
#'   It is what every ECG cart prints and what PhysioNet's twelve-lead databases
#'   are written in, so it is the order to hold a cohort in. `order = "cabrera"`
#'   gives the Cabrera sequence (aVL, I, -aVR, II, aVF, III, then the
#'   precordials), the recognised alternative, in which the frontal leads run
#'   contiguously from -30 to +120 degrees. Note that Cabrera displays *-aVR*;
#'   the lead named here is still `AVR`, and inverting its signal is the caller's
#'   to do.
#'
#'   A record's leads are stored in whatever order its source wrote them, and
#'   `as_ECG()` does not reorder them - annotation `channel` indices address
#'   signal columns by position, so permuting the columns would silently
#'   repoint every per-lead fiducial. Order at the point of use instead:
#'
#'   ```r
#'   features$lead <- lead_factor(features$lead)   # then sort, facet, or split
#'   signal <- get_signal(ecg)[, c("sample", as.character(ecg_leads()))]
#'   ```
#'
#'   `lead_factor()` canonicalises before ordering, so `aVR`, `av r` and `AV-R`
#'   all become `AVR`. A label that is not a surface lead becomes `NA`, which is
#'   deliberate: it shows up in a plot or a sort rather than being dropped
#'   quietly.
#'
#' @param order The display sequence. `"standard"` (default) or `"cabrera"`.
#' @param x A `character` vector of lead labels, or a factor of them.
#' @param drop Logical. If `TRUE`, levels no label uses are dropped, which is
#'   what a plot of a subset of leads usually wants. Default `FALSE`, so that
#'   records with different lead sets stay comparable.
#'
#' @return `ecg_leads()`, an ordered `factor` of twelve lead names.
#'   `lead_factor()`, an ordered `factor` of the same levels, one element per
#'   element of `x`.
#'
#' @references
#'
#' Kligfield P, Gettes LS, Bailey JJ, et al. Recommendations for the
#' standardization and interpretation of the electrocardiogram: part I.
#' *Circulation*. 2007;115(10):1306-1324.
#' \doi{10.1161/CIRCULATIONAHA.106.180200}
#'
#' @examples
#' ecg_leads()
#'
#' ecg_leads("cabrera")
#'
#' # Whatever they were called, and whatever order they came in
#' lead_factor(c("v2", "aVR", "II", "AV-L"))
#'
#' sort(lead_factor(c("V6", "I", "aVF", "V1")))
#'
#' # Not a surface lead, and said so rather than dropped
#' lead_factor(c("II", "CS 1-2"))
#'
#' @seealso [as_ECG()] for extracting the surface leads from a record, [ECG] for
#'   the class
#'
#' @name ecg_leads
#' @export
ecg_leads <- function(order = c("standard", "cabrera")) {
  order <- match.arg(order)
  standard <- as.character(.leads$ECG)

  sequence <- switch(
    order,
    standard = standard,
    # Frontal leads contiguous from -30 to +120 degrees; the precordials are
    # unaffected and follow as they do in the standard sequence
    cabrera = c(
      "AVL", "I", "AVR", "II", "AVF", "III",
      standard[startsWith(standard, "V")]
    )
  )

  factor(sequence, levels = sequence, ordered = TRUE)
}

#' @rdname ecg_leads
#' @export
lead_factor <- function(x, order = c("standard", "cabrera"), drop = FALSE) {
  levels <- as.character(ecg_leads(match.arg(order)))

  factor(canonical_leads(x), levels = levels, ordered = TRUE)[, drop = drop]
}

#' Surface ECG leads present among a set of channels
#'
#' @description Selects the surface ECG leads from a set of channel labels,
#'   keeping the order in which they were given. The result is named by canonical
#'   lead name and valued by the label as supplied, so it doubles as the lookup
#'   from "lead II" to whichever channel actually holds it.
#'
#' @details Matching ignores case, spaces, underscores and hyphens, so `aVR`,
#'   `av r` and `AV-R` all resolve to `AVR`.
#'
#' @param x A `character` vector of channel labels.
#'
#' @return A named `character` vector, possibly of length zero.
#'
#' @keywords internal
surface_leads <- function(x) {
  canonical <- canonical_leads(x)
  found <- !is.na(canonical)

  setNames(x[found], canonical[found])
}

#' Canonical lead name for each label, or `NA`
#'
#' @description The one place a written lead label is matched to a lead. Returns
#'   a vector parallel to its input, so a caller that must keep every element -
#'   [lead_factor()] - can, and one that wants only the matches -
#'   [surface_leads()] - drops the `NA`s itself.
#'
#' @param x A `character` vector of channel labels.
#'
#' @return A `character` vector the same length as `x`, `NA` where the label is
#'   not a surface lead.
#'
#' @keywords internal
canonical_leads <- function(x) {
  standard <- as.character(.leads$ECG)

  # `[[:space:]]` rather than `\\s`: in R's default TRE engine a backslash inside
  # a bracket expression is literal, so `[_\\s-]` matches the letter "s" and
  # silently mangles lead names
  key <- function(y) toupper(gsub("[_[:space:]-]", "", y))

  standard[match(key(as.character(x)), key(standard))]
}

#' Convert an EGM object to an ECG object
#'
#' @description Extracts the surface ECG from a record. Recognised surface leads
#'   are kept and renamed to their canonical form; every other channel is
#'   discarded. On a 12-lead recording this is a relabelling; on an
#'   electrophysiology study it is the step that separates the body-surface leads
#'   from the intracardiac ones.
#'
#' @details Channels are matched case-insensitively and ignoring separators, so
#'   `aVR`, `av r` and `AV-R` all resolve to `AVR`. A record with no surface
#'   leads at all is an error: an intracardiac channel cannot stand in for a
#'   surface lead, and the analyses gated on this class would otherwise return a
#'   number that looks reasonable and is not.
#'
#'   Annotation `channel` indices refer to positions in the original record. When
#'   channels are dropped those indices no longer address the leads they name, so
#'   a warning is raised if any channel-specific annotation is carried across.
#'
#'   For the same reason the kept leads stay in the order the record wrote them,
#'   rather than being put into display order. A channel index addresses a signal
#'   column by position, so permuting the columns would repoint every per-lead
#'   fiducial at a different lead - silently, since the indices remain valid.
#'   Renumbering them is not open to this function either: whether an annotator
#'   counted from zero or from one is a property of the file, and channel `0` is
#'   also how a fiducial says it belongs to no particular lead. Order at the
#'   point of use instead, with [ecg_leads()] and [lead_factor()].
#'
#' @param x An object of class `EGM`
#' @param ... Additional arguments
#'
#' @return An object of class `ECG`, holding its leads in the source record's
#'   order.
#'
#' @seealso [ecg_leads()] and [lead_factor()] for the display order, [ECG()] for
#'   the class, [extract_f_waves()] and [vcg()] for analyses that require it.
#'
#' @export
as_ECG <- function(x, ...) {
  if (!is_EGM(x)) {
    stop("Input must be of class 'EGM'", call. = FALSE)
  }

  channels <- names(x$signal)[-1]
  leads <- surface_leads(channels)

  if (length(leads) == 0) {
    stop(
      "No surface ECG leads found among the channels (",
      paste(channels, collapse = ", "),
      "). An <ECG> is the body-surface record; an intracardiac channel cannot ",
      "stand in for one.",
      call. = FALSE
    )
  }

  duplicated_leads <- unique(names(leads)[duplicated(names(leads))])
  if (length(duplicated_leads) > 0) {
    stop(
      "Several channels resolve to the same surface lead (",
      paste(duplicated_leads, collapse = ", "),
      "); which one is meant cannot be decided here.",
      call. = FALSE
    )
  }

  # The record is already exactly a surface ECG, canonically named. Rebuilding it
  # would regenerate the header and lose the fields - checksums, initial values,
  # channel colours - that only the original carries.
  if (identical(channels, names(leads))) {
    if (is_ECG(x)) {
      return(x)
    }
    return(new_ECG(x$signal, header = x$header, annotation = x$annotation))
  }

  dropped <- setdiff(channels, unname(leads))
  if (length(dropped) > 0) {
    message(
      "Keeping ",
      length(leads),
      " surface ECG lead(s) and dropping ",
      length(dropped),
      " other channel(s): ",
      paste(dropped, collapse = ", ")
    )
  }

  # Channel indices address positions in the original record. They cannot be
  # renumbered here without knowing whether the annotator counted from zero.
  per_channel <- any(vapply(
    x$annotation,
    function(a) !is.null(a$channel) && any(a$channel != 0L),
    logical(1)
  ))
  if (length(dropped) > 0 && per_channel) {
    warning(
      "Annotation `channel` indices refer to the original record and are not ",
      "renumbered when channels are dropped",
      call. = FALSE
    )
  }

  # Header rows are parallel to signal columns, so channels are kept by position.
  # Matching on the header `label` would break on records whose duplicate labels
  # were made unique when the header was built.
  signal <- x$signal
  header <- x$header
  record <- attributes(header)$record_line
  rows <- match(unname(leads), channels)

  new_ECG(
    signal = do.call(
      signal_table,
      c(
        list(sample = signal$sample),
        setNames(lapply(unname(leads), function(l) signal[[l]]), names(leads)),
        list(units = signal_units(signal))
      )
    ),
    header = header_table(
      record_name = record$record_name,
      number_of_channels = length(leads),
      frequency = record$frequency,
      samples = record$samples,
      start_time = record$start_time,
      ADC_saturation = record$ADC_saturation,
      storage_format = header$storage_format[rows],
      ADC_gain = header$ADC_gain[rows],
      ADC_baseline = header$ADC_baseline[rows],
      ADC_units = header$ADC_units[rows],
      ADC_zero = header$ADC_zero[rows],
      ADC_resolution = header$ADC_resolution[rows],
      label = names(leads),
      info_strings = attributes(header)$info_strings
    ),
    annotation = x$annotation
  )
}

#' Require a record to be a surface 12-lead ECG
#'
#' @description The gate for analyses defined only on the body-surface potential.
#'   It coerces an `EGM` to an [ECG] with [as_ECG()], then checks that the leads
#'   the analysis needs are present. Every ECG-only function opens with this call,
#'   so the contract lives in one place.
#'
#' @details Two levels of strictness are supported. With `leads = NULL` any
#'   non-empty surface lead set is accepted, which suits analyses that degrade
#'   gracefully - fibrillatory wave extraction reads each lead more or less
#'   independently and works, less precisely, on fewer of them. Naming `leads`
#'   makes them mandatory, which suits analyses that are undefined without a
#'   specific set - the Kors transform is a fixed linear combination of eight
#'   leads and cannot be evaluated when one is missing.
#'
#'   Reporting belongs to [as_ECG()], which says what it discarded, and to the
#'   `ECG` constructor, which warns on an incomplete lead set. This function only
#'   enforces.
#'
#' @param object An `EGM` or `ECG` object.
#' @param leads Optional `character` vector of canonical lead names that must be
#'   present. If `NULL` (default), any non-empty surface lead set is accepted.
#' @param what A `character` naming the analysis, used in error messages.
#'
#' @return An `ECG` object holding only surface leads.
#'
#' @keywords internal
require_ECG <- function(object, leads = NULL, what = "This analysis") {
  if (!is_EGM(object)) {
    stop(what, " requires an object of class <EGM> or <ECG>", call. = FALSE)
  }

  object <- as_ECG(object)

  missing_leads <- setdiff(leads, names(surface_leads(names(object$signal)[-1])))
  if (length(missing_leads) > 0) {
    stop(
      what,
      " requires the surface leads ",
      paste(leads, collapse = ", "),
      "; missing ",
      paste(missing_leads, collapse = ", "),
      call. = FALSE
    )
  }

  object
}
